# Generated by Django 5.1.6 on 2025-03-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchUser',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('userIconId', models.BigIntegerField(default=-1)),
                ('userDescription', models.CharField(blank=True, default='I am a free NPWS user!', max_length=140)),
                ('attribIds', models.JSONField()),
                ('friends', models.JSONField()),
                ('recentSearches', models.CharField(max_length=100)),
                ('keywordIds', models.JSONField()),
            ],
        ),
    ]
