# Generated by Django 5.1.6 on 2025-04-02 16:02

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllowedAttributeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="KeywordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="SearchUserAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SearchUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=64, validators=[main.models.validateUsername]
                    ),
                ),
                ("userIconId", models.BigIntegerField(default=-1)),
                (
                    "userDescription",
                    models.TextField(blank=True, default="I am a free NPWS user!"),
                ),
                ("recentSearches", models.CharField(max_length=100)),
                (
                    "friends",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.searchuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchUserAttributesMiddleTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.searchuserattributes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.searchuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchUserKeywordListMiddleTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keywordList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.keywordlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.searchuser",
                    ),
                ),
            ],
        ),
    ]
