# Generated by Django 5.1.6 on 2025-05-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchuser',
            name='userIconId',
        ),
        migrations.AddField(
            model_name='searchuser',
            name='userIcon',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
